# Dataset paths
path: /data/Bartscht/YOLO  # Base path
train: images/train        # Path to training images
val: images/val           # Path to validation images
test: images/test         # Path to test images

# Class configuration
nc: 7  # Number of classes

# Class names in ordered list
names:
  - Grasper
  - Bipolar
  - Hook
  - Scissors
  - Clipper
  - Irrigator
  - SpecimenBag

# Class weights
class_weights:
  0: 0.06
  1: 0.28
  2: 0.12
  3: 0.59
  4: 0.44
  5: 0.55
  6: 0